image: maven:3-eclipse-temurin-17

stages:
  - deploy

variables:
  SERVER_IP: "167.235.62.116"
  SERVER_USER: "eric"
  PROJECT_PATH: "/home/eric/union-gate/frontend"
  GIT_REPO: "https://$GIT_USERNAME:$GIT_PASSWORD@gitlab.com/union-gate/frontend.git"

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client sshpass git
    - mkdir -p ~/.ssh
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - |
      sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << EOF
      set -e
      echo "📂 Positionnement dans le projet..."
      
      
      cd $PROJECT_PATH
      echo "🔄 Mise à jour du code..."
      git pull origin master
      
    
      
      
      echo "✅ Déploiement terminé"
      EOF
  