// src/lib/fakeData/antenne.js

export const antennesData = [
    {
        id: 1,
        nom: "Siège National de Yaoundé",
        localisation: "Yaoundé, Centre - Quartier des Ministères",
        description: "L'antenne principale et centre névralgique de nos opérations nationales. Gère les affaires institutionnelles et la coordination générale.",
        membres: 5820,
        responsable: "Dr. Célestin Onana",
        telephone: "+237 699 11 22 33",
        email: "yaounde-siege@syndicmanager.org",
        horairesOuverture: "08:00 - 17:00",
        specialites: ["Administration", "Droit Social", "Relations Publiques"],
    },
    {
        id: 2,
        nom: "Antenne Économique de Douala",
        localisation: "Douala, Littoral - Bonanjo",
        description: "Focalisée sur les secteurs du commerce, de l'industrie et du transport. Un hub dynamique pour les acteurs économiques.",
        membres: 8950,
        responsable: "Mme. Aïssatou Bello",
        telephone: "+237 677 44 55 66",
        email: "douala-eco@syndicmanager.org",
        horairesOuverture: "08:30 - 17:30",
        specialites: ["Commerce International", "Logistique Portuaire", "Industrie"],
    },
    {
        id: 3,
        nom: "Pôle Agricole de Bafoussam",
        localisation: "Bafoussam, Ouest - Centre-ville",
        description: "Spécialisée dans le soutien aux agriculteurs et aux coopératives de la région de l'Ouest. Expertise en agronomie et développement rural.",
        membres: 3400,
        responsable: "Chef Jean-Marie Kamga",
        telephone: "+237 655 77 88 99",
        email: "bafoussam-agri@syndicmanager.org",
        horairesOuverture: "07:30 - 16:30",
        specialites: ["Agriculture", "Élevage", "Coopératives"],
    },
    {
        id: 4,
        nom: "Antenne du Grand Nord - Garoua",
        localisation: "Garoua, Nord - Quartier Résidentiel",
        description: "Couvre les régions du Nord, de l'Extrême-Nord et de l'Adamaoua, avec un focus sur l'élevage et le développement transfrontalier.",
        membres: 2100,
        responsable: "El Hadj Bouba Hamadou",
        telephone: "+237 698 12 34 56",
        email: "garoua-nord@syndicmanager.org",
        horairesOuverture: "08:00 - 16:00",
        specialites: ["Élevage", "Commerce Transfrontalier", "Développement local"],
    },
    {
        id: 5,
        nom: "Hub Technologique de Buea",
        localisation: "Buea, Sud-Ouest - Silicon Mountain",
        description: "Le cœur de l'innovation et de la tech. Rassemble les développeurs, startups et professionnels du numérique de la région.",
        membres: 1500,
        responsable: "Ms. Emmanuela Ade",
        telephone: "+237 675 54 32 10",
        email: "buea-tech@syndicmanager.org",
        horairesOuverture: "09:00 - 18:00",
        specialites: ["Technologie", "Startups", "Formation Numérique"],
    },
    {
        id: 6,
        nom: "Antenne Côtière de Kribi",
        localisation: "Kribi, Sud - Près du Port",
        description: "Dédiée aux secteurs du tourisme, de la pêche et des activités portuaires de la cité balnéaire.",
        membres: 980,
        responsable: "M. David Mpondo",
        telephone: "+237 691 92 93 94",
        email: "kribi-cotier@syndicmanager.org",
        horairesOuverture: "08:30 - 17:00",
        specialites: ["Tourisme", "Pêche", "Activités Maritimes"],
    },
];