// src/lib/fakeData/exploreSyndicatFake.js

export const exploresyndicat = [
    {
        id: 1,
        name: "Union Nationale des Enseignants du Supérieur (UNES)",
        type: "Éducation",
        image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8MTB8fGVkdWNhdGlvbnxlbnwwfHx8fDE3MTI4NzMwNzB8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Yaoundé, Centre",
        members: 2580,
        rating: 4.8,
        certified: true,
        recommended: true,
        founded: 1998,
        specialties: ["Recherche", "Pédagogie", "Droit Universitaire"],
        popularityScore: 92,
        description: "Défend les droits et les intérêts des enseignants et chercheurs du supérieur au Cameroun."
    },
    {
        id: 2,
        name: "Syndicat des Travailleurs de la Santé Publique (STSP)",
        type: "Santé",
        image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8N3x8aGVhbHRoY2FyZXxlbnwwfHx8fDE3MTI4NzMxMDV8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Douala, Littoral",
        members: 5300,
        rating: 4.7,
        certified: true,
        recommended: true,
        founded: 2005,
        specialties: ["Soins infirmiers", "Santé publique", "Administration hospitalière"],
        popularityScore: 88,
        description: "Œuvre pour l'amélioration des conditions de travail et de la qualité des soins dans le secteur public de la santé."
    },
    {
        id: 3,
        name: "Fédération des Artisans du Cameroun (FEDARTIS)",
        type: "Artisanat",
        image: "https://images.unsplash.com/photo-1595821733973-b14a94379b9f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8NHx8Y3JhZnRzbWFufGVufDB8fHx8fDE3MTI4NzMxMzR8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Bafoussam, Ouest",
        members: 850,
        rating: 4.5,
        certified: false,
        recommended: false,
        founded: 2010,
        specialties: ["Menuiserie", "Couture", "Maroquinerie"],
        popularityScore: 75,
        description: "Soutient et promeut le développement des métiers de l'artisanat à travers le pays."
    },
    {
        id: 4,
        name: "Syndicat des Transporteurs Routiers Interurbains (SYNTRI)",
        type: "Transport",
        image: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8Mnx8YnVzfGVufDB8fHx8fDE3MTI4NzMyMTJ8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Yaoundé, Centre",
        members: 8900,
        rating: 4.6,
        certified: true,
        recommended: true,
        founded: 1995,
        specialties: ["Transport de passagers", "Logistique", "Sécurité routière"],
        popularityScore: 95,
        description: "L'organisation leader pour les professionnels du transport routier interurbain, assurant sécurité et fiabilité."
    },
    {
        id: 5,
        name: "Association des Commerçants du Marché Central (ACMC)",
        type: "Commerce",
        image: "https://images.unsplash.com/photo-1528698827591-e19ccd7e23ec?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8MTF8fG1hcmtldCUyMHN0YWxsfGVufDB8fHx8fDE3MTI4NzMyNDZ8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Douala, Littoral",
        members: 450,
        rating: 4.2,
        certified: false,
        recommended: false,
        founded: 2018,
        specialties: ["Vente au détail", "Produits frais", "Import-Export"],
        popularityScore: 68,
        description: "Représente et défend les intérêts des commerçants opérant au sein du marché central."
    },
    {
        id: 6,
        name: "Guilde des Développeurs et Tech Innovators (GDTI)",
        type: "Technologie",
        image: "https://images.unsplash.com/photo-1550439062-609e1531270e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8OHx8dGVjaG5vbG9neXxlbnwwfHx8fDE3MTI4NzMyNzl8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Buea, Sud-Ouest",
        members: 1150,
        rating: 4.9,
        certified: true,
        recommended: true,
        founded: 2019,
        specialties: ["Développement Web", "IA", "FinTech", "Cybersécurité"],
        popularityScore: 98,
        description: "Le hub de l'innovation technologique, connectant les meilleurs talents du numérique au Cameroun."
    },
    {
        id: 7,
        name: "Collectif des Agriculteurs du Moungo (CAM)",
        type: "Agriculture",
        image: "https://images.unsplash.com/photo-1590152957961-0737119859e0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8Nnx8Y29mZmVlJTIwZmFybXxlbnwwfHx8fDE3MTI4NzMzMTJ8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Nkongsamba, Littoral",
        members: 1500,
        rating: 4.7,
        certified: true,
        recommended: false,
        founded: 1985,
        specialties: ["Café", "Cacao", "Poivre de Penja"],
        popularityScore: 85,
        description: "Union des producteurs agricoles visant à améliorer les rendements et l'accès aux marchés."
    },
    {
        id: 8,
        name: "Syndicat National des Journalistes du Cameroun (SNJC)",
        type: "Média",
        image: "https://images.unsplash.com/photo-1455849318743-b2233052fcff?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8OHx8am91cm5hbGlzbXxlbnwwfHx8fDE3MTI4NzMzNDR8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Yaoundé, Centre",
        members: 670,
        rating: 4.4,
        certified: true,
        recommended: false,
        founded: 1960,
        specialties: ["Presse écrite", "Audiovisuel", "Liberté de la presse"],
        popularityScore: 81,
        description: "Veille à la défense de la liberté de la presse et à la protection des journalistes."
    },
    {
        id: 9,
        name: "Ordre National des Ingénieurs de Génie Civil (ONIGC)",
        type: "BTP",
        image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8M3x8Y29uc3RydWN0aW9ufGVufDB8fHx8fDE3MTI4NzMzNzN8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Douala, Littoral",
        members: 3200,
        rating: 4.8,
        certified: true,
        recommended: true,
        founded: 2001,
        specialties: ["Infrastructures", "Bâtiments", "Urbanisme"],
        popularityScore: 90,
        description: "Régule et promeut l'excellence dans la pratique du génie civil sur le territoire national."
    },
    {
        id: 10,
        name: "Association des Hôteliers et Restaurateurs de Kribi (AHRK)",
        type: "Tourisme",
        image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8Mnx8aG90ZWx8ZW5wfDB8fHx8fDE3MTI4NzM0MDR8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Kribi, Sud",
        members: 120,
        rating: 4.6,
        certified: false,
        recommended: false,
        founded: 2012,
        specialties: ["Hébergement", "Restauration", "Loisirs"],
        popularityScore: 78,
        description: "Fédère les acteurs du tourisme pour faire de Kribi une destination de premier choix."
    },
    {
        id: 11,
        name: "Syndicat des Acteurs de la Mode et du Design (SAMOD)",
        type: "Artisanat",
        image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8M3x8ZmFzaGlvbnxlbnwwfHx8fDE3MTI4NzM0MzZ8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Douala, Littoral",
        members: 350,
        rating: 4.7,
        certified: false,
        recommended: true,
        founded: 2020,
        specialties: ["Stylisme", "Modélisme", "Textile"],
        popularityScore: 83,
        description: "La plateforme des créateurs et designers de mode, promouvant le savoir-faire local."
    },
    {
        id: 12,
        name: "Union des Pêcheurs Artisans de Limbé (UPAL)",
        type: "Pêche",
        image: "https://images.unsplash.com/photo-1541538336294-8a4341355415?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wzNTc5fDB8MXxzZWFyY2h8Mnx8ZmlzaGluZyUyMGJvYXR8ZW5wfDB8fHx8fDE3MTI4NzM0NjZ8MA&ixlib=rb-4.0.3&q=80&w=800",
        location: "Limbé, Sud-Ouest",
        members: 780,
        rating: 4.3,
        certified: false,
        recommended: false,
        founded: 1992,
        specialties: ["Pêche côtière", "Transformation du poisson", "Aquaculture"],
        popularityScore: 72,
        description: "Défense des intérêts des pêcheurs artisans et promotion d'une pêche durable et responsable."
    },
];